### ISSUE TITLE
memcache plugin is borken with syntax error

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-maas#152]
This is neither a list nor a dictionary:

```
MEMCACHE_METRICS = {'total_items': 'items',
        'get_hits': 'cache_hits',
        'get_misses': 'cache_misses',
        'total_connections': 'connections']
```

**Comment by mattt416** [comment]
Still seeing this:

```
root@jenkins-151-node1:/usr/lib/rackspace-monitoring-agent/plugins# python memcached_status.py 172.29.236.133
status okay
metric memcache_api_local_status uint32 1
Traceback (most recent call last):
  File "memcached_status.py", line 77, in <module>
    main(args)
  File "memcached_status.py", line 68, in main
    metric('memcache_%s' % metric, 'uint64', stats[metric], unit)
TypeError: 'str' object is not callable
root@jenkins-151-node1:/usr/lib/rackspace-monitoring-agent/plugins#
```
