### ISSUE TITLE
Swift MaaS Replication Checks Failing - Traceback - KeyError: 'replication_type'

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-maas#172]
MaaS installation from RPC 10.1.2...

### Account Replication
```
root@lab-byron-upgrade-n07:/usr/lib/rackspace-monitoring-agent/plugins# python swift-recon.py --ring-type account replication
status error main()\n File "swift-recon.py", line 352, in main\n stats = swift_replication(args.ring)\n File "swift-recon.py", line 156, in swift_replication\n replication_statistics[rep_dict.pop('replication_type')] = rep_dict\nKeyError: 'replication_type'\n
Traceback (most recent call last):
  File "swift-recon.py", line 365, in <module>
    main()
  File "swift-recon.py", line 352, in main
    stats = swift_replication(args.ring)
  File "swift-recon.py", line 156, in swift_replication
    replication_statistics[rep_dict.pop('replication_type')] = rep_dict
KeyError: 'replication_type'
```

### Container Replication
```
root@lab-byron-upgrade-n07:/usr/lib/rackspace-monitoring-agent/plugins# python swift-recon.py --ring-type container replication
status error main()\n File "swift-recon.py", line 352, in main\n stats = swift_replication(args.ring)\n File "swift-recon.py", line 156, in swift_replication\n replication_statistics[rep_dict.pop('replication_type')] = rep_dict\nKeyError: 'replication_type'\n
Traceback (most recent call last):
  File "swift-recon.py", line 365, in <module>
    main()
  File "swift-recon.py", line 352, in main
    stats = swift_replication(args.ring)
  File "swift-recon.py", line 156, in swift_replication
    replication_statistics[rep_dict.pop('replication_type')] = rep_dict
KeyError: 'replication_type'
```

### Object Replication
```
root@lab-byron-upgrade-n07:/usr/lib/rackspace-monitoring-agent/plugins# python swift-recon.py --ring-type object replication
status error main()\n File "swift-recon.py", line 352, in main\n stats = swift_replication(args.ring)\n File "swift-recon.py", line 156, in swift_replication\n replication_statistics[rep_dict.pop('replication_type')] = rep_dict\nKeyError: 'replication_type'\n
Traceback (most recent call last):
  File "swift-recon.py", line 365, in <module>
    main()
  File "swift-recon.py", line 352, in main
    stats = swift_replication(args.ring)
  File "swift-recon.py", line 156, in swift_replication
    replication_statistics[rep_dict.pop('replication_type')] = rep_dict
KeyError: 'replication_type'
```

**Comment by claco** [comment]
So @sigmavirus24 and I have stumbled on this before. I swear it was a combo of a) we fixed it (maybe we didn't backport), and b) there is no replication related states without a replication network:  https://github.com/rcbops/rpc-heat/pull/3

**Comment by sigmavirus24** [comment]
Looks like A). I'll backport it ASAP

**Comment by sigmavirus24** [comment]
See #173

**Comment by byronmccollum** [comment]
Further investigation shows replication failed to start, which is the root of the failures above.

**Comment by nrb** [comment]
@byronmccollum, @sigmavirus24 is this resolved, then?

**Comment by sigmavirus24** [comment]
looks it
