### ISSUE TITLE
swift_quarantine_check throws status error unrecognized command "quarantaine"

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#205]
current version out of the master branch :
```
status error out = subprocess.check_output(command)\n  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output\n    raise CalledProcessError(retcode, cmd, output=output)\nCalledProcessError: Command '['swift-recon', '-q']' returned non-zero exit status 1\n
Traceback (most recent call last):
  File "./swift-recon.py", line 380, in <module>
    main()
  File "./swift-recon.py", line 369, in main
    stats = get_stats_from(args)
  File "./swift-recon.py", line 353, in get_stats_from
    stats = swift_quarantine()
  File "./swift-recon.py", line 235, in swift_quarantine
    regexp)
  File "./swift-recon.py", line 114, in recon_stats_dicts
    recon_output(for_ring, options)))
  File "./swift-recon.py", line 60, in recon_output
    out = subprocess.check_output(command)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['swift-recon', '-q']' returned non-zero exit status 1
```

**Comment by sigmavirus24** [comment]
Because you've misspelled "quarantine" as "quarantaine"? Did you want it to autocorrect that for you?

**Comment by sigmavirus24** [comment]
"quarantaine" does not exist in either rpc-extras or rpc-maas. Can you elaborate on where that typo is coming from?

**Comment by BjoernT** [comment]
Updated description

**Comment by sigmavirus24** [comment]
To reproduce this, can you provide the version of swift that you're testing against and perhaps any information that swift-recon provides?

Could you also provide the results of running `swift-recon -q` directly? (For reference, swift-recon is called with `-1` [here](https://github.com/rcbops/rpc-maas/blob/master/swift-recon.py#L234).)

**Comment by BjoernT** [comment]
swift03:/usr/lib/rackspace-monitoring-agent/plugins# swift-recon -q
===============================================================================
--> Starting reconnaissance on 3 hosts
===============================================================================
[2015-05-10 19:37:38] Checking quarantine
Traceback (most recent call last):
  File "/usr/local/bin/swift-recon", line 24, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/swift/cli/recon.py", line 1087, in main
    reconnoiter.main()
  File "/usr/local/lib/python2.7/dist-packages/swift/cli/recon.py", line 1077, in main
    self.quarantine_check(hosts)
  File "/usr/local/lib/python2.7/dist-packages/swift/cli/recon.py", line 776, in quarantine_check
    if response['policies']:
KeyError: 'policies'

**Comment by sigmavirus24** [comment]
In that case, this is clearly a bug in swift-recon, whatever version you happen to have installed. Please file a bug with swift about this.

**Comment by BjoernT** [comment]
See https://bugs.launchpad.net/openstack-ansible/+bug/1453599
